<a href="https://colab.research.google.com/github/darwish1998/Blog/blob/master/introduction_of_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundemental concept of of tennsorflow
* introduction tensorflow



In [ ]:
import tensorflow as tf
print(tf.__version__)



2.8.0


In [ ]:
#@title Default title text
# creating tensors with tf.constant

scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
scalar.ndim

0

In [ ]:
# create a vector
vector = tf.constant([23,32])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([23, 32], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create matrix 
matrix = tf.constant([[12,10],[23,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 10],
       [23, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

sample_data/
